version: '3'

services:
    web:
        build: ./docker/nginx
        ports:
            - 80:80
        volumes:
            - ./code:/var/www/html
            - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    phpfpm:
        build: ./docker/php
        ports:
            - 9000:9000
        volumes:
            - ./code:/var/www/html
        networks:
            - code-network

networks:
    code-network:
        driver: bridge
