version: "3.3"

services:
    # Nginx service
    web:
        container_name: ${WEB_CONTAINER}
        image: nginx:alpine
        ports:
            - ${WEB_PORT}:80
        volumes:
            - ./code:/var/www/html
            - ./config/nginx/site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - ${PROJECT_NAME}-network
    
    # PHP service           
    phpfpm:
        container_name: ${APP_CONTAINER}
        build:
          args:
            user: ${LOCAL_USER}
            uid: ${LOCAL_UID}
          context: ./config/php
        tty: true
        volumes:
            - ./code:/var/www/html
        networks:
            - ${PROJECT_NAME}-network

networks:
    just-php-network:
        driver: bridge
